### PR TITLE
Migrate to chocolatey package

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/riboseinc/metanorma-windows-setup/issues/13
 - https://github.com/riboseinc/metanorma-windows-setup/issues/9

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 Why are we using Ruby 2.3 path here but 2.5 in the other one?

**Comment by CAMOBAP** [comment]
@ronaldtse good catch I will switch to 2.5

Initially I started with 2.3 for this repo, but because DLL loading issue I decided to switch to 2.5 (the same issue which described in https://github.com/riboseinc/metanorma-cli#installation-notes-for-windows )

PR updated

**Comment by ronaldtse** [comment]
@CAMOBAP795 this build is still failing...

**Comment by CAMOBAP** [comment]
@ronaldtse I will have a look in 3h

**Comment by CAMOBAP** [comment]
@ronaldtse there was a problem which as solved in https://github.com/riboseinc/metanorma-windows-setup/pull/12 and because this was old PR I completely forgot about it(

Shortly speaking in our appveyor.yml we always dowloaded install.bat from `master`, this was a problem, I have changed it to sue variable

CI in progress

**Pull request merged**
