### PR TITLE
Splitting the docker and native install scripts

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Done, @ronaldtse let me know once you finished review I will change some links from `powershell` to `master` branch

**Comment by ronaldtse** [comment]
In the README the Docker setup steps should be pointing to “docker.bat” for download. 

Also, it doesn’t look like the code has been much changed — I haven’t tried it yet but yesterday the gem install step didn’t work on my Windows VM?

**Comment by CAMOBAP** [comment]
> In the README the Docker setup steps should be pointing to “docker.bat” for download.

Good point I will fix it

> Also, it doesn’t look like the code has been much changed — I haven’t tried it yet but yesterday the gem install step didn’t work on my Windows VM?

Unfortunately it's difficult to investigate without logs, BTW what is os version on your VM?

**Comment by ronaldtse** [comment]
It’s Windows 10 with Edge: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by CAMOBAP** [comment]
@ronaldtse sublime and openssl packages was removed, BTW regarding gem installation problem could you please send `metanorma_install.log`?

**Pull request merged**
