### PR TITLE
Install all dependencies to run metanorma locally

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 thanks -- looks like we're almost there!

**Comment by CAMOBAP** [comment]
@ronaldtse Done

**Comment by ronaldtse** [comment]
Thanks! Can you help update the appveyor test to also run git clone on a document (https://github.com/riboseinc/unece-cefact-recommendation-42) and compile it using the newly installed toolchain?

I.e. just clone the repo, and run “make all”?

**Comment by CAMOBAP** [comment]
@ronaldtse but this is exactly what it do already https://github.com/riboseinc/unece-cefact-recommendation-42/pull/1/files#diff-180360612c6b8c4ed830919bbb4dd459

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes, but I want to also add that test into this repo (metanorma-windows-setup) so we can check whether the document can be built within Windows using this script. Thanks!

**Comment by ronaldtse** [comment]
Let me merge this first and file an additional issue

**Pull request merged**
