### PR TITLE
Add install script to install metanorma on windows in one line

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP795 ! Is there a way we can ensure this script continuously works, such as using a CI?

**Comment by ronaldtse** [comment]
We also need to fix the "directory mounting" issue after installing `docker-machine` on Windows.

**Comment by CAMOBAP** [comment]
> Is there a way we can ensure this script continuously works, such as using a CI?

@ronaldtse good point, I think the only free option is to use https://www.appveyor.com/, I will integrate it

> We also need to fix the "directory mounting" issue after installing docker-machine on Windows.

I plan to finish it in scope of PR to https://github.com/riboseinc/unece-cefact-recommendation-42 idea is to create softlink to `C;\Users` with `mklink.exe`, PR on the way

**Comment by ronaldtse** [comment]
Good call @CAMOBAP795 , I've signed up this repo for AppVeyor here: https://ci.appveyor.com/project/ronaldtse/metanorma-windows-setup

Not sure how to replace my username with the organization name?

**Comment by ronaldtse** [comment]
Can we merge this now? Thanks.

**Comment by CAMOBAP** [comment]
> Can we merge this now? Thanks.

Unfortunately not ready yet, but I hope it will be in near 1-2h

**Comment by CAMOBAP** [comment]
@ronaldtse I think it's good to merge

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Pull request merged**
